/* eslint-disable no-console -- CLI export script */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import Database from "better-sqlite3";

import { chunkPresetBlob } from "./terraformPresetBlobStorage.mjs";
import { verifyTerraformImportPresetTestDb } from "./terraformImportPresetDb.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "../..");
const OUTPUT_DIR = path.join(REPO_ROOT, "functions/generated");
const OUTPUT_PATH = path.join(OUTPUT_DIR, "presets-data.sql");

const sourcePath = process.argv[2]
  ? path.resolve(process.argv[2])
  : path.join(REPO_ROOT, "terraform-import-presets.db");

function sqlLiteral(value) {
  if (value === null || value === undefined) {
    return "NULL";
  }
  return `'${String(value).replace(/'/g, "''")}'`;
}

function writeInsert(lines, table, columns, rows) {
  if (rows.length === 0) {
    return;
  }
  const colList = columns.join(", ");
  for (const row of rows) {
    const values = row.map((cell) => sqlLiteral(cell)).join(", ");
    lines.push(`INSERT INTO ${table} (${colList}) VALUES (${values});`);
  }
}

if (!fs.existsSync(sourcePath)) {
  console.error(
    `Source DB not found: ${sourcePath}\nRun yarn seed:terraform-presets first.`,
  );
  process.exit(1);
}

const { presetCount, withContent } =
  verifyTerraformImportPresetTestDb(sourcePath);
if (presetCount < 1 || withContent < 1) {
  console.error(
    `Source DB is incomplete (${withContent}/${presetCount} presets with plan+dot). Run yarn seed:terraform-presets.`,
  );
  process.exit(1);
}

// verifyTerraformImportPresetTestDb opens the DB writable and re-syncs stack text
// into terraform_import_artifacts (duplicate of preset_stacks + blob_chunks).
// D1 cannot ingest those multi-MB INSERTs; preset import uses stacks/chunks only.
const dbPrep = new Database(sourcePath);
dbPrep.prepare(`DELETE FROM terraform_import_artifacts`).run();
dbPrep.close();

const db = new Database(sourcePath, { readonly: true });

const presets = db
  .prepare(
    `SELECT id, name, description, builtin, view, root_path, created_at, updated_at
     FROM terraform_import_presets
     ORDER BY builtin DESC, name ASC`,
  )
  .all();

const stacks = db
  .prepare(
    `SELECT preset_id, sort_order, stack_id, label, plan_path, dot_path, state_path,
            plan_text, dot_text, state_text
     FROM terraform_import_preset_stacks
     ORDER BY preset_id ASC, sort_order ASC`,
  )
  .all();

const tfdRows = db
  .prepare(
    `SELECT preset_id, sort_order, path, content
     FROM terraform_import_preset_tfd
     ORDER BY preset_id ASC, sort_order ASC`,
  )
  .all();

const compositions = db
  .prepare(
    `SELECT id, name, description, default_view, tfd_content, created_at, updated_at
     FROM terraform_import_compositions
     ORDER BY id ASC`,
  )
  .all();

db.close();

const blobChunkRows = [];
const stackRows = stacks.map((row) => {
  const plan = chunkPresetBlob(row.plan_text);
  const dot = chunkPresetBlob(row.dot_text);
  const state = chunkPresetBlob(row.state_text);

  for (const [blobKind, blobKey, packed] of [
    ["plan", row.stack_id, plan],
    ["dot", row.stack_id, dot],
    ["state", row.stack_id, state],
  ]) {
    packed.chunks.forEach((data, chunkIndex) => {
      blobChunkRows.push([row.preset_id, blobKind, blobKey, chunkIndex, data]);
    });
  }

  return [
    row.preset_id,
    row.sort_order,
    row.stack_id,
    row.label,
    row.plan_path,
    row.dot_path,
    row.state_path,
    plan.inline,
    dot.inline,
    state.inline,
  ];
});

const tfdInsertRows = tfdRows.map((row) => {
  const packed = chunkPresetBlob(row.content);
  packed.chunks.forEach((data, chunkIndex) => {
    blobChunkRows.push([row.preset_id, "tfd", row.path, chunkIndex, data]);
  });
  return [row.preset_id, row.sort_order, row.path, packed.inline];
});

const lines = [
  "-- Generated by yarn export:terraform-presets-d1 — idempotent re-import",
  "DELETE FROM terraform_import_preset_blob_chunks;",
  "DELETE FROM terraform_import_preset_tfd;",
  "DELETE FROM terraform_import_preset_stacks;",
  "DELETE FROM terraform_import_compositions;",
  "DELETE FROM terraform_import_artifacts;",
  "DELETE FROM terraform_import_presets;",
  "",
];

writeInsert(
  lines,
  "terraform_import_presets",
  [
    "id",
    "name",
    "description",
    "builtin",
    "view",
    "root_path",
    "created_at",
    "updated_at",
  ],
  presets.map((row) => [
    row.id,
    row.name,
    row.description,
    row.builtin,
    row.view,
    row.root_path,
    row.created_at,
    row.updated_at,
  ]),
);

// Artifacts omitted from D1 export (see DELETE above).

writeInsert(
  lines,
  "terraform_import_compositions",
  [
    "id",
    "name",
    "description",
    "default_view",
    "tfd_content",
    "created_at",
    "updated_at",
  ],
  compositions.map((row) => [
    row.id,
    row.name,
    row.description,
    row.default_view,
    row.tfd_content,
    row.created_at,
    row.updated_at,
  ]),
);

writeInsert(
  lines,
  "terraform_import_preset_stacks",
  [
    "preset_id",
    "sort_order",
    "stack_id",
    "label",
    "plan_path",
    "dot_path",
    "state_path",
    "plan_text",
    "dot_text",
    "state_text",
  ],
  stackRows,
);

writeInsert(
  lines,
  "terraform_import_preset_tfd",
  ["preset_id", "sort_order", "path", "content"],
  tfdInsertRows,
);

writeInsert(
  lines,
  "terraform_import_preset_blob_chunks",
  ["preset_id", "blob_kind", "blob_key", "chunk_index", "data"],
  blobChunkRows,
);

fs.mkdirSync(OUTPUT_DIR, { recursive: true });
fs.writeFileSync(OUTPUT_PATH, `${lines.join("\n")}\n`, "utf8");

let maxLine = 0;
for (const line of lines) {
  if (line.length > maxLine) {
    maxLine = line.length;
  }
}

console.log(
  `Exported ${presets.length} preset(s) (${withContent} with plan+dot), ${blobChunkRows.length} blob chunk(s), max SQL line ${maxLine} chars`,
);
console.log(`  → ${path.relative(REPO_ROOT, OUTPUT_PATH)}`);
console.log("\nPush to Cloudflare D1 (remote):");
console.log(
  "  yarn push:terraform-presets-d1:prod     # production (master / tfdraw.dev)",
);
console.log("  yarn push:terraform-presets-d1:preview  # branch previews");
console.log("  yarn push:terraform-presets-d1          # both");
console.log("\nFirst-time preview schema:");
console.log(
  "  npx wrangler d1 execute tfdraw-presets-preview --remote --file=./functions/presets-schema.sql",
);
