version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "01:00"
    reviewers:
      - lipis
    assignees:
      - lipis
    open-pull-requests-limit: 20

  - package-ecosystem: npm
    directory: /src/packages/excalidraw/
    schedule:
      interval: weekly
      day: sunday
      time: "01:00"
    reviewers:
      - ad1992
    assignees:
      - ad1992
    open-pull-requests-limit: 20

  - package-ecosystem: npm
    directory: /src/packages/utils/
    schedule:
      interval: weekly
      day: sunday
      time: "01:00"
    reviewers:
      - ad1992
    assignees:
      - ad1992
    open-pull-requests-limit: 20
