sonar.projectKey=excalidraw-tf
sonar.projectName=excalidraw-tf
sonar.sourceEncoding=UTF-8

sonar.sources=packages/excalidraw,packages/common,packages/element,packages/math,packages/utils,excalidraw-app,functions
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.ts,**/*.test.tsx,**/__snapshots__/**,packages/backend/terraform/**,dev-docs/**,examples/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.newCode.referenceBranch=master
