"""Relevance filter for graph drawing / layout literature."""

from __future__ import annotations

LAYOUT_KEYWORDS = frozenset(
    {
        "graph",
        "layout",
        "drawing",
        "drawn",
        "layer",
        "layered",
        "layering",
        "crossing",
        "sugiyama",
        "orthogonal",
        "planar",
        "node",
        "edge",
        "vertices",
        "visualization",
        "visualisation",
        "diagram",
        "hierarchical",
        "dag",
        "directed",
        "undirected",
        "force-directed",
        "stress",
        "majorization",
        "compound",
        "cluster",
        "grouped",
        "port",
        "routing",
        "elk",
        "kieler",
        "dagre",
        "dot",
        "neato",
        "uml",
        "network",
        "topology",
        "embedding",
        "coordinates",
        "rank",
        "assignment",
        "bundling",
        "sankey",
        "metro",
        "tree",
        "radial",
        "hypergraph",
        "confluence",
        "aesthetic",
        "geometric",
    }
)

OFF_TOPIC_KEYWORDS = frozenset(
    {
        "genome",
        "genomic",
        "microbiome",
        "microbiota",
        "rna",
        "dna",
        "protein",
        "cancer",
        "tumor",
        "tumour",
        "oncology",
        "clinical trial",
        "patient",
        "hospital",
        "covid",
        "sars-cov",
        "vaccine",
        "epidemiology",
        "pathogen",
        "bacteria",
        "fungal",
        "metagenom",
        "transcriptom",
        "proteom",
        "chromosome",
        "hi-c",
        "sequencing",
        "phylogen",
        "ecology",
        "agriculture",
        "crop",
        "livestock",
        "neurodegener",
        "alzheimer",
        "parkinson",
        "psychiatric",
        "depression",
        "schizophrenia",
        "cardiovascular",
        "diabetes",
        "obesity",
        "pharmacolog",
        "drug discovery",
        "machine learning algorithms real-world",
    }
)


def is_layout_relevant(title: str, abstract: str | None = None) -> bool:
    """Return True if title/abstract looks graph-layout related."""
    hay = f"{title} {abstract or ''}".lower()
    if any(k in hay for k in OFF_TOPIC_KEYWORDS):
        return False
    return any(k in hay for k in LAYOUT_KEYWORDS)
