name: "🚀 Feature Request"
description: "Suggest an idea for a new feature."
title: "[Feature]: "
labels: ["feature"]
body:
  - type: textarea
    id: problem-description
    attributes:
      label: "Is your feature request related to a problem? Please describe."
      description: "A clear and concise description of what the problem is. Ex. 'I'm always frustrated when...'"
    validations:
      required: true

  - type: textarea
    id: suggested-solution
    attributes:
      label: "Suggested Solution"
      description: "Describe the solution you'd like in a clear and concise way."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "Describe any alternative solutions or features you've considered."

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Add any other context or screenshots about the feature request here."