// Generated by Wrangler by running `wrangler types --experimental-include-runtime=./worker-runtime.d.ts`

interface Env {
  DURABLE_ROOM: DurableObjectNamespace<
    import("./cloudflare/worker").DurableRoom
  >;
}
