export default {
  type: "excalidraw",
  version: 2,
  source: "https://excalidraw.com",
  elements: [
    {
      type: "text",
      version: 372,
      versionNonce: 716288438,
      isDeleted: false,
      id: "ddt0nha9Bxbe4I_Qa3005",
      fillStyle: "solid",
      strokeWidth: 1,
      strokeStyle: "solid",
      roughness: 1,
      opacity: 100,
      angle: 0,
      x: 627.1504211425781,
      y: -518.0598297119141,
      strokeColor: "#000000",
      backgroundColor: "#fd7e1488",
      width: 499,
      height: 175,
      seed: 1845203046,
      groupIds: [],
      strokeSharpness: "sharp",
      boundElementIds: ["7Slyz-S4KAlDN8LXnX_0h"],
      fontSize: 20,
      fontFamily: 1,
      text:
        "Latin\nPack my box with five dozen liquor jugs\nPACK MY BOX WITH FIVE DOZEN LIQUOR JUGS\npack my box with five dozen liquor jugs\n\n[ ] ( ) < > ? ! . , ; ' \" @ # $ €% ^ & * ~ ` / \\\n0 1 2 3 4 5 6 7 8 9",
      baseline: 168,
      textAlign: "center",
      verticalAlign: "top",
    },
    {
      type: "text",
      version: 117,
      versionNonce: 1472457898,
      isDeleted: false,
      id: "yKW5tkHyouqYB3blkigop",
      fillStyle: "hachure",
      strokeWidth: 1,
      strokeStyle: "solid",
      roughness: 1,
      opacity: 100,
      angle: 0,
      x: 507.6504211425781,
      y: -225.03644180297852,
      strokeColor: "#000000",
      backgroundColor: "transparent",
      width: 738,
      height: 75,
      seed: 1121051335,
      groupIds: [],
      strokeSharpness: "sharp",
      boundElementIds: ["OekqvztxmBAq96wPVysya"],
      fontSize: 20,
      fontFamily: 1,
      text:
        "Greek\nΑ  Β  Γ  Δ  Ε  Ζ  Η  Θ  Ι  Κ  Λ  Μ  Ν  Ξ  Ο  Π  Ρ  Σ Τ  Υ  Φ  Χ  Ψ  Ω\nα β γ δ ε ζ η θ ι κ λ μ ν ξ ο π ρ σ ς τ υ φ χ ψ ω",
      baseline: 68,
      textAlign: "center",
      verticalAlign: "top",
    },
    {
      type: "text",
      version: 87,
      versionNonce: 1748896502,
      isDeleted: false,
      id: "up2FWcmRpqZjhhtyd8Rpe",
      fillStyle: "hachure",
      strokeWidth: 1,
      strokeStyle: "solid",
      roughness: 1,
      opacity: 100,
      angle: 0,
      x: 516.1504211425781,
      y: -32.01305389404297,
      strokeColor: "#000000",
      backgroundColor: "transparent",
      width: 721,
      height: 75,
      seed: 1135053319,
      groupIds: [],
      strokeSharpness: "sharp",
      boundElementIds: ["ZHf0focsl7z7vJ7KFea9p"],
      fontSize: 20,
      fontFamily: 1,
      text:
        "Russian\nА Б В Г Д Е Ё Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ъ Ы Ь Э Ю Я\nа б в г д е ё ж з и й к л м н о п р с т у ф х ц ч ш щ ъ ы ь э ю я",
      baseline: 68,
      textAlign: "center",
      verticalAlign: "top",
    },
  ],
  appState: {
    gridSize: null,
    viewBackgroundColor: "#ffffff",
  },
};
