name: Build Docker image

on:
  push:
    branches:
      - release

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - run: docker build --pull -t excalidraw .
